import { Result } from './result';
import { DiscoveredBackend } from './backendDiscoverer';

export interface StorageExportBundle {
  exportedAt: string;
  domain: string;
  storage: {
    localStorage: Record<string, string>;
    sessionStorage: Record<string, string>;
    cookies: Record<string, string>;
    indexedDB: Record<string, any>;
  };
  presets?: any[];
  discoveredBackend?: DiscoveredBackend;
  provenanceHistory?: any[];
}

export interface MockServerOptions {
  port?: number;
  domain?: string;
  storageData: {
    localStorage?: Record<string, string>;
    sessionStorage?: Record<string, string>;
    cookies?: Record<string, string>;
    indexedDB?: Record<string, any>;
  };
  discoveredBackend?: DiscoveredBackend;
}

export interface GeneratedMockServerPackage {
  filename: string;
  serverCode: string;
  packageJson: string;
  readme: string;
  exportJson: string;
}

export function generateStorageExportBundle(
  domain: string,
  storage: StorageExportBundle['storage'],
  presets?: any[],
  discoveredBackend?: DiscoveredBackend,
  provenanceHistory?: any[]
): StorageExportBundle {
  return {
    exportedAt: new Date().toISOString(),
    domain: domain || 'localhost',
    storage: {
      localStorage: storage?.localStorage || {},
      sessionStorage: storage?.sessionStorage || {},
      cookies: storage?.cookies || {},
      indexedDB: storage?.indexedDB || {},
    },
    presets: presets || [],
    discoveredBackend,
    provenanceHistory: provenanceHistory || [],
  };
}

export function generateStandaloneMockServer(
  options: MockServerOptions
): Result<GeneratedMockServerPackage, Error> {
  try {
    const port = options.port || 3000;
    const domain = options.domain || 'localhost';
    const storageData = {
      localStorage: options.storageData?.localStorage || {},
      sessionStorage: options.storageData?.sessionStorage || {},
      cookies: options.storageData?.cookies || {},
      indexedDB: options.storageData?.indexedDB || {},
    };
    const discoveredBackend = options.discoveredBackend;

    const bundle = generateStorageExportBundle(domain, storageData, [], discoveredBackend);
    const exportJson = JSON.stringify(bundle, null, 2);

    const endpoints = discoveredBackend?.endpointsFound || [
      '/api/v1/users',
      '/api/v1/auth/login',
      '/api/v1/products',
      '/api/v1/config',
    ];

    const serverCode = `/**
 * 🚀 Standalone Development Mock Server
 * Auto-generated by Browser Storage Suite
 * 
 * Target Domain: ${domain}
 * Default Port: ${port}
 * 
 * Usage:
 *   node mock-server.js
 *   or: PORT=8080 node mock-server.js
 */

import http from 'node:http';

const PORT = process.env.PORT || ${port};

// Mock Storage State initialized from exported session
const mockStorage = ${JSON.stringify(storageData, null, 2)};

// Discovered Endpoint Catalog
const registeredEndpoints = ${JSON.stringify(endpoints, null, 2)};

function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS, PATCH');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With');
}

function sendJson(res, statusCode, data) {
  setCorsHeaders(res);
  res.writeHead(statusCode, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data, null, 2));
}

function parseJsonBody(req) {
  return new Promise((resolve) => {
    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', () => {
      try {
        resolve(body ? JSON.parse(body) : {});
      } catch {
        resolve({});
      }
    });
  });
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, \`http://\${req.headers.host || 'localhost'}\`);
  const pathname = url.pathname;
  const method = req.method.toUpperCase();

  const timestamp = new Date().toLocaleTimeString();
  console.log(\`[\${timestamp}] \${method} \${pathname}\`);

  // Handle CORS Preflight
  if (method === 'OPTIONS') {
    setCorsHeaders(res);
    res.writeHead(204);
    res.end();
    return;
  }

  // 1. Storage API - GET /api/v1/storage
  if (pathname === '/api/v1/storage' && method === 'GET') {
    return sendJson(res, 200, {
      status: 'success',
      targetDomain: '${domain}',
      storage: mockStorage,
    });
  }

  // 2. Storage API by Target - GET /api/v1/storage/:target
  const storageTargetMatch = pathname.match(/^\\/api\\/v1\\/storage\\/(localStorage|sessionStorage|cookies|indexedDB)$/);
  if (storageTargetMatch && method === 'GET') {
    const target = storageTargetMatch[1];
    return sendJson(res, 200, {
      status: 'success',
      target,
      entries: mockStorage[target] || {},
    });
  }

  // 3. Storage API Set Item - POST /api/v1/storage/:target
  if (storageTargetMatch && method === 'POST') {
    const target = storageTargetMatch[1];
    const body = await parseJsonBody(req);
    if (!body.key) {
      return sendJson(res, 400, { status: 'error', message: 'Missing "key" parameter' });
    }
    mockStorage[target] = mockStorage[target] || {};
    mockStorage[target][body.key] = String(body.value || '');
    return sendJson(res, 200, {
      status: 'success',
      message: \`Key "\${body.key}" updated in \${target}\`,
      key: body.key,
      value: mockStorage[target][body.key],
    });
  }

  // 4. Storage API Delete Item - DELETE /api/v1/storage/:target/:key
  const storageDeleteMatch = pathname.match(/^\\/api\\/v1\\/storage\\/(localStorage|sessionStorage|cookies|indexedDB)\\/(.+)$/);
  if (storageDeleteMatch && method === 'DELETE') {
    const target = storageDeleteMatch[1];
    const key = decodeURIComponent(storageDeleteMatch[2]);
    if (mockStorage[target] && key in mockStorage[target]) {
      delete mockStorage[target][key];
      return sendJson(res, 200, { status: 'success', message: \`Key "\${key}" deleted from \${target}\` });
    }
    return sendJson(res, 404, { status: 'error', message: \`Key "\${key}" not found in \${target}\` });
  }

  // 5. Dynamic Mock Routes Discovered from Backend / OpenAPI Spec
  if (registeredEndpoints.some((ep) => pathname.startsWith(ep) || ep.startsWith(pathname))) {
    if (pathname.includes('auth') || pathname.includes('login')) {
      return sendJson(res, 200, {
        status: 'success',
        token: mockStorage.localStorage?.user_auth_token || 'bearer_mock_jwt_dev_token_999',
        user: { id: 1, name: 'Admin Developer', role: 'super_admin' },
      });
    }
    if (pathname.includes('user')) {
      return sendJson(res, 200, [
        { id: 1, name: 'Admin Developer', email: 'admin@company.org', role: 'admin' },
        { id: 2, name: 'Test User', email: 'user@company.org', role: 'user' },
      ]);
    }
    return sendJson(res, 200, {
      status: 'success',
      route: pathname,
      mockedFromStorage: mockStorage.localStorage || {},
    });
  }

  // Fallback Wildcard Mock Handler
  return sendJson(res, 200, {
    status: 'success',
    message: 'Wildcard Development Mock Endpoint',
    route: pathname,
    method,
    query: Object.fromEntries(url.searchParams),
    storageSample: mockStorage.localStorage || {},
  });
});

server.listen(PORT, () => {
  console.log(\`\n======================================================\`);
  console.log(\`🚀 Standalone Development Mock Server is Live!\`);
  console.log(\`📡 Listening at: http://localhost:\${PORT}\`);
  console.log(\`📦 Domain: ${domain}\`);
  console.log(\`💡 Storage API Endpoint: http://localhost:\${PORT}/api/v1/storage\`);
  console.log(\`======================================================\n\`);
});
`;

    const packageJson = JSON.stringify(
      {
        name: 'browser-storage-mock-server',
        version: '1.0.0',
        description: `Standalone Development Mock Server for ${domain}`,
        main: 'mock-server.js',
        type: 'module',
        scripts: {
          start: 'node mock-server.js',
        },
      },
      null,
      2
    );

    const readme = `# 🚀 Standalone Development Mock Server (${domain})

Automatically generated by **Browser Storage Suite**.

## ⚡ Quickstart

Run the server on your local machine with **Zero Dependencies**:

\`\`\`bash
node mock-server.js
\`\`\`

Or via NPM:

\`\`\`bash
npm start
\`\`\`

Default Port: \`http://localhost:${port}\`  
Custom Port Example: \`PORT=8080 node mock-server.js\`

---

## 🛠️ Storage REST API Endpoints

| Method | Endpoint | Description |
| :--- | :--- | :--- |
| \`GET\` | \`/api/v1/storage\` | Returns complete mock storage state |
| \`GET\` | \`/api/v1/storage/:target\` | Returns entries for target (\`localStorage\`, \`sessionStorage\`, \`cookies\`, \`indexedDB\`) |
| \`POST\` | \`/api/v1/storage/:target\` | Sets key/value (\`{ "key": "my_key", "value": "my_val" }\`) |
| \`DELETE\` | \`/api/v1/storage/:target/:key\` | Deletes key from storage |

---

## 🌐 Registered Mock Routes

${endpoints.map((ep) => `- \`${ep}\``).join('\n')}

All endpoints have **CORS preflight & wildcard headers** enabled out-of-the-box for seamless frontend development.
`;

    return Result.ok({
      filename: `mock-server-${domain.replace(/[^a-zA-Z0-9]/g, '_')}.js`,
      serverCode,
      packageJson,
      readme,
      exportJson,
    });
  } catch (err) {
    return Result.err(err instanceof Error ? err : new Error(String(err)));
  }
}
